# The URL the site will be built for
base_url = "https://talecember.kestrels-and-roses.rocks"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true
default_language = "fr"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[languages.fr]
generate_feed = true

[languages.fr.translations]
binomial_name = "Binom"
conservation_status = "Statut"
feeds = "Flux"
humidity = "Humidité"
language = "Langue"
temperature_range = "Températures supportées"
title = "Talecember"
type = "Type"
updated = "Dernière mise à jour"
vernacular_name = "Nom vernaculaire"

[languages.en]
generate_feed = true

[languages.en.translations]
binomial_name = "Binomial name"
conservation_status = "Conservation status"
feeds = "Feeds"
humidity = "Humidity"
language = "Language"
temperature_range = "Temperature range"
title = "Talecember"
type = "Type"
updated = "Last update"
vernacular_name = "Vernacular name"